import { useEffect, useState } from "react";
import { Loader2, QrCode as QrCodeIcon } from "lucide-react";

import { getQrSvg } from "@/lib/tauri";

/** Result of the last render request, tagged with the URL it belongs to. */
type QrResult = { url: string; svg: string } | { url: string; svg: null };

/**
 * Inline SVG QR code for the share URL.
 *
 * The markup is generated by the Rust core from a URL the core itself built,
 * and it is drawn with `currentColor` so it follows the app theme.
 */
export function QrCode({ url }: { url: string }) {
  const [result, setResult] = useState<QrResult | null>(null);

  useEffect(() => {
    let cancelled = false;

    getQrSvg(url)
      .then((svg) => {
        if (!cancelled) setResult({ url, svg });
      })
      .catch(() => {
        if (!cancelled) setResult({ url, svg: null });
      });

    return () => {
      cancelled = true;
    };
  }, [url]);

  // Deriving from the tagged result means a URL change shows the spinner
  // again without a second state update inside the effect.
  const current = result?.url === url ? result : null;

  if (!current) {
    return (
      <div className="flex h-[200px] w-[200px] items-center justify-center rounded-lg border border-border">
        <Loader2 className="size-4 animate-spin text-muted-foreground" aria-hidden />
      </div>
    );
  }

  if (current.svg === null) {
    return (
      <div className="flex h-[200px] w-[200px] flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-border text-muted-foreground">
        <QrCodeIcon className="size-5" aria-hidden />
        <span className="text-xs">QR code unavailable</span>
      </div>
    );
  }

  return (
    <div className="flex flex-col items-center gap-3">
      <div
        className="size-[200px] rounded-lg bg-white p-2 text-black [&>svg]:size-full"
        // Trusted input: the SVG comes from the core's own QR renderer.
        dangerouslySetInnerHTML={{ __html: current.svg }}
        role="img"
        aria-label="QR code for the share address"
      />
      <p className="text-xs text-muted-foreground">Scan to open on another device</p>
    </div>
  );
}
